spring.application.name=contact2.0

spring.datasource.url=jdbc:mysql://localhost:3306/contact2.0
spring.datasource.username=root
spring.datasource.password=***REMOVED***



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=606977326472-3mupq43pcieponc5evf8aofmqp6k090t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile


spring.security.oauth2.client.registration.github.client-id=Iv23liooTiCiaZaMcR8f
spring.security.oauth2.client.registration.github.client-secret=231b364310ad9c7732801264352233d2d4ca2137
spring.security.oauth2.client.registration.github.scope=email,profile


cloudinary.cloud.name=dvznt84hj
cloudinary.api.key=***REMOVED***
cloudinary.api.secret=***REMOVED***



spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=***REMOVED***
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.domain_name=shivam@demomailtrap.co


